#!/bin/bash
# Train a 3D medical VLM for report generation on M3D-Cap using pseudo reports.
#
# Conditions reported in the paper (Table 1):
#   - 100, 500, 2000, 10000 pseudo-report samples
#
# Pseudo reports are generated by scripts/01_generate_pseudo_reports.sh
# Each pseudo-report condition shares the same base model and only the
# training subset size differs.
#
# Usage:
#   bash scripts/03_train_caption.sh <n_pseudo_samples> <output_dir>
#   e.g. bash scripts/03_train_caption.sh 500 ./outputs/finetune_cap_pseudo500

set -e

N_PSEUDO=${1:-500}
OUTPUT_DIR=${2:-./outputs/finetune_cap_pseudo${N_PSEUDO}}
SUMMARIES_JSON=${3:-./outputs/m3d_cap_summaries_qwen3.json}
DATA_ROOT=${4:-./data/M3D_Cap_npy}

mkdir -p "$OUTPUT_DIR"

echo "==================================================================="
echo "Training report generation: ${N_PSEUDO} pseudo samples"
echo "==================================================================="
echo "Output dir:    $OUTPUT_DIR"
echo "Summaries:     $SUMMARIES_JSON"
echo "Data root:     $DATA_ROOT"
echo ""

python lamed/train/train.py \
    --model_name_or_path microsoft/Phi-3-mini-4k-instruct \
    --model_type phi3 \
    --vision_tower vit3d \
    --pretrain_vision_model ./checkpoints/M3D-CLIP/pretrained_ViT.bin \
    --pretrain_mm_mlp_adapter ./checkpoints/M3D-LaMed-Phi-3-4B/mm_projector.bin \
    --data_root "$DATA_ROOT" \
    --cap_data_path "$DATA_ROOT/M3D_Cap.json" \
    --summaries_json_path "$SUMMARIES_JSON" \
    --s2d "$N_PSEUDO" \
    --s3d 0 \
    --w2d 1.0 \
    --w3d 0.0 \
    --bf16 True \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --learning_rate 1e-4 \
    --weight_decay 0.0 \
    --warmup_ratio 0.05 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_strategy steps \
    --save_steps 500 \
    --save_total_limit 2 \
    --gradient_checkpointing True \
    --dataloader_num_workers 2 \
    --report_to tensorboard \
    --output_dir "$OUTPUT_DIR"

echo ""
echo "Done. Trained model at: $OUTPUT_DIR"
