#!/bin/bash
# Train a 3D medical VLM for segmentation on Duke Breast Cancer MRI.
#
# Conditions reported in the paper (Table 5/6):
#   - GT-only         : 50 expert masks
#   - Pseudo-only     : 50 pseudo masks (MedSAM)
#   - GT + 100 Pseudo : 50 GT + 100 pseudo masks
#   - GT + 500 Pseudo : 50 GT + 500 pseudo masks
#
# Pseudo masks are generated by scripts/02_generate_pseudo_masks.sh.
# Train/test CSVs are produced by data_prep/prepare_duke.py and
# data_prep/prepare_train_csv.py.
#
# Usage:
#   bash scripts/04_train_segmentation.sh <train_csv> <output_dir>
#   e.g. bash scripts/04_train_segmentation.sh \
#           ./finetune_data/duke_gt_plus_pseudo/train.csv \
#           ./outputs/finetune_duke_gt_plus_pseudo

set -e

TRAIN_CSV=${1:-./finetune_data/duke_gt/train.csv}
OUTPUT_DIR=${2:-./outputs/finetune_duke_gt}
TEST_CSV=${3:-./finetune_data/duke_test.csv}

mkdir -p "$OUTPUT_DIR"

echo "==================================================================="
echo "Training segmentation"
echo "==================================================================="
echo "Train CSV:  $TRAIN_CSV"
echo "Test CSV:   $TEST_CSV"
echo "Output dir: $OUTPUT_DIR"
echo ""

python lamed/train/train_text_guided_refseg.py \
    --model_name_or_path microsoft/Phi-3-mini-4k-instruct \
    --model_type phi3 \
    --vision_tower vit3d \
    --pretrain_vision_model ./checkpoints/M3D-CLIP/pretrained_ViT.bin \
    --pretrain_mm_mlp_adapter ./checkpoints/M3D-LaMed-Phi-3-4B/mm_projector.bin \
    --segmentation_module segvol \
    --pretrain_seg_module ./checkpoints/SegVol/pytorch_model.bin \
    --data_root ./ \
    --refseg_data_train_path "$TRAIN_CSV" \
    --refseg_data_test_path "$TEST_CSV" \
    --bf16 True \
    --num_train_epochs 5 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --eval_strategy no \
    --save_strategy steps \
    --save_steps 500 \
    --save_total_limit 2 \
    --learning_rate 5e-6 \
    --weight_decay 0.0 \
    --warmup_ratio 0.03 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --gradient_checkpointing True \
    --remove_unused_columns False \
    --dataloader_pin_memory True \
    --dataloader_num_workers 2 \
    --report_to tensorboard \
    --output_dir "$OUTPUT_DIR"

echo ""
echo "Done. Trained model at: $OUTPUT_DIR"
